batch_size: 32
seq_len: 100
predict_len: 0
label_len: 0
do_eval: True
epoch: 1
training: True 
anomaly_ratio: 1
task: anomaly
to_static_train: False
use_amp: False
amp_level: O2



dataset: 
  name: TSADDataset
  dataset_root: ./dataset/
  train_path: ./dataset/ts_anomaly_examples/train.csv
  val_path: ./dataset/ts_anomaly_examples/test.csv
  scale: True
  time_feat: False


info_params:
  freq: 1
  label_col: "label"
  feature_cols: ['feature_1', 'feature_2', 'feature_3', 'feature_24']


model: 
  name: NonStationary_AD
  model_cfg:
    c_in: 5
    factor: 3
    p_hidden_dims: [32, 32]
    d_model: 64
    d_ff: 64
    optimizer_params:
      learning_rate: 0.001
      gamma: 0.5

loss: mse

test:
  stride: 1 

output: 'output/'