batch_size: 16
seq_len: 96
predict_len: 336
do_eval: True
sampling_stride: 1
epoch: 2
to_static_train: False
use_amp: False
amp_level: O2

dataset: 
  name: TSDataset
  dataset_root: ts_dataset_examples
  train_path: ts_dataset_examples/train.csv
  val_path: ts_dataset_examples/val.csv
  time_feat: False
  scale: True

info_params:
  time_col: date

model: 
  name: RLinearModel
  model_cfg:
    c_in: 1
    dropout: 0.0
    optimizer_params:
      learning_rate: 0.001
      gamma: 0.5
    patience: 10

test:
  stride: 1

  



