batch_size: 32
seq_len: 720
predict_len: 96
do_eval: True
sampling_stride: 1
epoch: 2
to_static_train: False
use_amp: False
amp_level: O2


dataset: 
  name: TSDataset
  dataset_root: ts_dataset_examples
  train_path: ts_dataset_examples/train.csv
  val_path: ts_dataset_examples/val.csv
  time_feat: True
  use_holiday: True
  scale: True

info_params:
  time_col: date

model: 
  name: TiDE
  model_cfg:
    c_in: 321
    num_encoder_layers: 2
    use_revin: False
    drop_prob: 0.5
    hidden_size: 1024
    decoder_output_dim: 8
    temporal_decoder_hidden: 64
    optimizer_params:
      learning_rate: 0.00099
      gamma: 0.5
    patience: 10
    #pretrain: non-station_torch.pdparams

test:
  stride: 1

  



