batch_size: 32 #
seq_len: 96 #
predict_len: 96 #
do_eval: True #
sampling_stride: 1
epoch: 2 # max_epochs
to_static_train: False
use_amp: False
amp_level: O2


dataset: 
  name: TSDataset
  dataset_root: ts_dataset_examples
  train_path: ts_dataset_examples/train.csv
  val_path: ts_dataset_examples/val.csv
  time_feat: True
  use_holiday: False
  scale: True

info_params:
  time_col: date
  
model: 
  name: TimesNetModel
  model_cfg:
    c_in: 321 #
    c_out: 321 #
    e_layers: 2 #
    num_kernels: 6 #
    d_model: 32 #
    d_ff: 32 #
    top_k: 5 # 
    renorm: Null # 
    optimizer_params:
      learning_rate: 0.0001
      gamma: 0.5

test:
  stride: 1 # 